# Generated by Django 2.2.3 on 2020-08-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('score', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=500, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['city'],
            },
        ),
    ]
