# Generated by Django 2.2.3 on 2020-01-16 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('location', models.CharField(max_length=1000, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('isAvailible', models.BooleanField(null=True)),
                ('room_no', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('pictures', models.CharField(max_length=2000, null=True)),
                ('city', models.CharField(max_length=500, null=True)),
                ('address', models.CharField(max_length=5000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
