# Generated by Django 2.2.3 on 2020-06-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='isAvailible',
            new_name='available',
        ),
        migrations.AddField(
            model_name='ads',
            name='image',
            field=models.ImageField(default='ad-default.jpg', upload_to='Ads_Pix'),
        ),
        migrations.AddField(
            model_name='ads',
            name='smokeFree',
            field=models.BooleanField(null=True),
        ),
    ]
