# Generated by Django 2.2.3 on 2020-08-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisements', '0003_ads_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='pictures',
        ),
    ]
